rarity = [
    "Common",
    "Rare",
    "Team of the Week",
    "Icon",
    "Winter Wildcards",
    "UT Heroes",
    "NumeroFUT",
    "Total Rush",
    "Trailblazers",
    "SQUAD FOUNDATIONS",
    "Thunderstruck",
    "Globetrotters",
    "Centurions",
    "Ultimate Succession",
    "UCL Road to the Knockouts",
    "Track Stars",
    "FC Pro Live",
    "Team of the Year",
    "Winter Wildcards Icon",
    "Winter Wildcards Hero",
    "Ballon d'Or",
    "TOTY Honourable Mentions",
    "Thunderstruck ICON",
    "World Tour",
    "Champions Mastery",
    "Squad Battles Mastery",
    "Rivals Mastery",
    "Flashback Player",
    "Prime Hero",
    "TOTY Icon",
    "Centurions Icon",
    "Track Stars Hero",
    "UEL Road to the Knockouts",
    "Ultimate Succession Icon",
    "Winter Champions",
    "Showdown Plus",
    "UWCL Road to the Knockouts",
    "End Of An Era",
    "On This Day Icon",
    "POTM SERIE A",
    "POTM Premier League",
    "Liga F POTM",
    "Moments",
    "POTM LALIGA EA SPORTS",
    "POTM Ligue 1",
    "POTM Bundesliga",
    "Ultimate Succession Hero",
    "Mode Mastery",
    "UECL Road to the Knockouts",
    "SHOWDOWN",
    "Ultimate Cover Star",
    "On This Day Hero",
    "TOTY Eras 2002 ICON",
    "TOTY Evolution",
    "Winter Wildcards Evolution",
    "Centurions Evolution",
    "Bundesliga POTM",
    "Purple Evo",
    "Dynamic Duos",
    "UCL Road to the Final",
    "Legendary",
    "Standard",
    "POTM EREDIVISIE",
    "Ultimate",
    "Premium",
    "Vintage",
    "Epic",
    "Select",
    "Squad Building Challenge",
    "Ones to Watch",
    "Ultimate Team Champions",
    "Ultimate Team Champions Pro",
    "Pro Player",
    "Domestic Man of the Match",
    "Evolutions III",
    "Evolutions II",
    "Evolutions I",
    "In-Progress Evolution",
    "Origin Hero"
]

chemistryStyle = [
    "Sniper",
    "Finisher",
    "Deadeye",
    "Marksman",
    "Hawk",
    "Artist",
    "Architect",
    "Powerhouse",
    "Maestro",
    "Engine",
    "Sentinel",
    "Guardian",
    "Gladiator",
    "Backbone",
    "Anchor",
    "Hunter",
    "Catalyst",
    "Shadow",
    "Wall",
    "Shield",
    "Cat",
    "Glove",
    "GK Basic"
]
